version: 2
formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html
  tools:
    python: "3.9"

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx_rtd_theme
        - sphinx-autodoc-typehints
        - enum-tools[sphinx]