version: 2
formats: []

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

  